title: Maarten Craeynest
description: Maarten's portfolio
url: "https://mcraeynest.github.io"
baseurl: ""
remote_theme: piazzai/cvless

# site settings
taglong: Senior C++/Rust developer
tagshort: C++/Rust Dev

# author settings
author:
  name: Maarten Craeynest
  email: mcraeynest@gmail.com
photo: assets/files/photo.jpg

joblines:
  - Senior C++ developer
  - Swift
  - Avenue Adele 1, 1310 La Hulpe
address: Leuven, Belgium
phone: +32 474 48 05 89

# profile links
profile:
  linkedin: https://www.linkedin.com/in/maarten-craeynest/
  github: https://github.com/mcraeynest
  cv: false
  # facebook: https://www.facebook.com/username
  # x: https://x.com/username
  # mastodon: https://mastodon.social/@username
  # bluesky: https://bsky.app/profile/username.bsky.social
  # instagram: https://www.instagram.com/username
  # xing: https://www.xing.com/profile/username
  # medium: https://medium.com/@username
  # stackoverflow: https://stackoverflow.com/users/0000000/username

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
