title: Maarten Craeynest
description: Maarten's portfolio
baseurl: ""
url: "https://mcraeynest.github.io/mcraeyne.github.io/"
remote_theme: piazzai/cvless

# site settings
taglong: Jekyll theme for a beautiful online CV
tagshort: mcraeyne portfolio

# author settings
author:
  name: Maarten Craeynest
  email: mcraeynest@gmail.com
photo: assets/files/photo.jpg

joblines:
  - University of Jekyll
  - Department of Themes
  - 123 Main St, Anytown, USA
address: Foobar Hall 1.23
phone: +1 234 567 890

# profile links
profile:
  facebook: https://www.facebook.com/username
  x: https://x.com/username
  mastodon: https://mastodon.social/@username
  bluesky: https://bsky.app/profile/username.bsky.social
  instagram: https://www.instagram.com/username
  linkedin: https://www.linkedin.com/in/username
  xing: https://www.xing.com/profile/username
  stackoverflow: https://stackoverflow.com/users/0000000/username
  medium: https://medium.com/@username
  github: https://github.com/mcraeynest
  cv: true

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
